### ISSUE TITLE
Outdated gen_ssl

### ISSUE THREAD

**Issue by wakaru44** [cdrage/composefiles#1]
Hi

The URL in gen_ssl seems out of date. Sensu 0.21 seems no longer supported, failing to generate the certs.

I updated the url manually from 

```
wget http://sensuapp.org/docs/0.21/files/sensu_ssl_tool.tar
```

to 

```
wget http://sensuapp.org/docs/0.23/files/sensu_ssl_tool.tar
```

And it worked.

**Comment by cdrage** [comment]
Thanks man! :) I'll go ahead and update it @wakaru44
